# Generated by Django 2.1.3 on 2018-12-01 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_after', models.TextField(verbose_name='Completed work')),
                ('requirements', models.TextField(max_length=500)),
                ('permission_letter_url', models.FileField(blank=True, upload_to='')),
                ('legal_agreement_url', models.FileField(blank=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Limitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('authority', models.IntegerField()),
                ('reason', models.CharField(default='', max_length=100)),
                ('restriction', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('street_address', models.CharField(blank=True, max_length=200)),
                ('restrictions', models.ManyToManyField(blank=True, to='map.Limitation')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField(verbose_name='Uploaded image')),
                ('description', models.TextField(default='', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(default=None, verbose_name='Uploaded sketch')),
                ('sketch_status', models.CharField(blank=True, default='', max_length=100)),
                ('restrictions', djongo.models.fields.ListField(null=True, verbose_name='sketch_restrictions')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sketches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_status', models.CharField(default='initialized', max_length=50)),
                ('generic_status', models.CharField(default='initialized', max_length=100)),
                ('art_permission', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sketch',
            name='workload',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='map.Workload'),
        ),
        migrations.AddField(
            model_name='photoupload',
            name='workload',
            field=models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='map.Workload'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='sketch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='art_work', to='map.Sketch'),
        ),
    ]
