# Generated by Django 2.1.2 on 2018-12-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sketch',
            name='restrictions',
        ),
        migrations.AlterField(
            model_name='photoupload',
            name='photo',
            field=models.TextField(blank=True, verbose_name='Uploaded image'),
        ),
        migrations.AlterField(
            model_name='sketch',
            name='sketch_status',
            field=models.CharField(blank=True, default='uploaded', max_length=100),
        ),
    ]
