# Generated by Django 2.1.2 on 2018-11-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='position',
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
