# Generated by Django 2.1.2 on 2018-11-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20181111_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitation',
            name='restrictions',
        ),
        migrations.AddField(
            model_name='limitation',
            name='restriction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='street_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
