# Generated by Django 2.1.2 on 2018-11-11 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approval', '0002_hierarchy_userhierarchywrapper'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_after', models.URLField(default='', max_length=500)),
                ('requirements', models.TextField(max_length=500)),
                ('permission_letter_url', models.URLField(default='', max_length=500)),
                ('legal_agreement_url', models.URLField(default='', max_length=500)),
                ('artist_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoUpload',
            fields=[
                ('photo', models.ImageField(upload_to='', verbose_name='Uploaded image')),
                ('photo_url', models.URLField(default='', max_length=500)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='map.Location')),
                ('description', models.TextField(default='', max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(default='', max_length=500)),
                ('sketchStatus', models.CharField(blank=True, default='', max_length=100)),
                ('artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restrictions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.CustomLimitation')),
            ],
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_upload', models.URLField(default='', max_length=500)),
                ('frontend_status', models.CharField(default='', max_length=100)),
                ('complete_work', models.BooleanField()),
                ('status', models.CharField(default='', max_length=100)),
                ('art_permission', models.FileField(upload_to='')),
            ],
        ),
    ]
