# Generated by Django 2.1.2 on 2018-11-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20181111_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
